name: "publish"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
            args: ""

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Disable initramfs update
        if: startsWith(matrix.platform, 'ubuntu-22.04')
        run: |
          if [ -f /etc/initramfs-tools/update-initramfs.conf ]; then
            sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
          else
            echo "No initramfs config file found, skipping."
          fi

      - name: Disable man-db update
        if: startsWith(matrix.platform, 'ubuntu-22.04')
        run: sudo rm -f /var/lib/man-db/auto-update || true

      - uses: awalsh128/cache-apt-pkgs-action@latest
        if: startsWith(matrix.platform, 'ubuntu-22.04')
        with:
          packages: libwebkit2gtk-4.1 libayatana-appindicator3-1 librsvg2-dev patchelf libgtk-3-dev pkg-config libglib2.0-dev libpango1.0-dev libcairo2-dev libgdk-pixbuf2.0-dev libatk1.0-dev libharfbuzz-dev pkg-config xdg-utils

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install frontend dependencies
        run: yarn ci

      - name: Build the app
        run: yarn run build

      - name: Generate changelog
        run: |
          set -e
          source $HOME/.cargo/env
          git cliff --tag ${{ steps.tag.outputs.tag_name }} > ../changelog.md

      - name: Publish Release on Gitea
        uses: akkuman/gitea-release-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: ${{ steps.tag.outputs.tag_name }}
          body_path: changelog.md
          files: src-tauri/target/release/bundle/appimage/openlink_*.AppImage
          prerelease: true
